# Generated by Django 5.1.4 on 2026-09-30 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('framework', 'Framework'), ('database', 'Database'), ('devops', 'DevOps'), ('soft_skill', 'Soft skill'), ('language', 'Language'), ('tool', 'Tool'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('manual', 'Manual entry'), ('ai_generated', 'AI generated')], default='upload', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('extracted_skills', models.ManyToManyField(blank=True, related_name='resume_versions', to='resumes.skill')),
            ],
            options={
                'verbose_name': 'resume version',
                'verbose_name_plural': 'resume versions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'status'], name='resumes_res_user_id_3262c5_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_primary'], name='resumes_res_user_id_ce3f75_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['resume', 'is_current'], name='resumes_res_resume__6ba24a_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.UniqueConstraint(fields=('resume', 'version_number'), name='unique_resume_version_number'),
        ),
    ]
