# Generated by Django 5.1.4 on 2026-09-30 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(db_index=True)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('extra_skills', models.JSONField(blank=True, default=list)),
                ('is_saved', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('user_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job match',
                'verbose_name_plural': 'job matches',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-score'], name='matches_job_user_id_91da31_idx'), models.Index(fields=['user', 'is_saved'], name='matches_job_user_id_9c8aa6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'resume', 'job'), name='unique_user_resume_job_match')],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.CharField(blank=True, db_index=True, max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('importance', models.FloatField(default=0.5)),
                ('learning_resources', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='resumes.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='resumes.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill gap',
                'verbose_name_plural': 'skill gaps',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'priority'], name='matches_ski_user_id_f82ca1_idx'), models.Index(fields=['user', 'is_resolved'], name='matches_ski_user_id_f8ee50_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'resume', 'skill', 'target_role'), name='unique_user_resume_skill_target_gap')],
            },
        ),
    ]
