# Generated by Django 5.1.4 on 2026-09-30 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual entry'), ('api', 'API'), ('feed', 'RSS / feed'), ('approved_web', 'Approved web source')], db_index=True, default='manual', max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'job source',
                'verbose_name_plural': 'job sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('remote_policy', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='onsite', max_length=20)),
                ('seniority', models.CharField(blank=True, max_length=50)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], db_index=True, default='open', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='resumes.skill')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobsource')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-posted_at'], name='jobs_job_status_0b37a6_idx'), models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
