"""
Orchestrator: coordinates multi-agent workflows.

The orchestrator:
- Validates a WorkflowPlan
- Resolves input placeholders (${step_id.field})
- Dispatches steps to the appropriate agents
- Enforces overall budgets
- Aggregates results into a single AgentResult

IMPORTANT: The orchestrator does NOT make decisions on its own.
It executes a plan that was either:
- Constructed manually by the caller
- Generated by a planning step (Phase 7C)
"""

from typing import Any

from agents.context import AgentContext
from agents.exceptions import (
    AgentBudgetExceededError,
    AgentError,
)
from agents.plan import PlanStatus, PlanStep, WorkflowPlan
from agents.registry import AgentRegistry
from agents.result import AgentResult, AgentStatus


class Orchestrator:
    """
    Coordinates execution of a WorkflowPlan.

    Usage:
        orch = Orchestrator(context)
        plan = WorkflowPlan(goal="Analyze resume", steps=[...])
        result = orch.execute_plan(plan)
    """

    def __init__(self, context: AgentContext) -> None:
        self.context = context
        self._step_results: dict[str, AgentResult] = {}

    # ==========================================================
    # Public API
    # ==========================================================

    def execute_plan(self, plan: WorkflowPlan) -> AgentResult:
        """
        Execute a plan end-to-end.

        Returns:
            AgentResult with the combined output of all steps.
        """
        # 1. Validate
        errors = plan.validate()
        if errors:
            return AgentResult.failed("Plan validation failed: " + "; ".join(errors))

        plan.status = PlanStatus.RUNNING
        self.context.log(
            "orchestrator_plan_start",
            {
                "plan_id": plan.plan_id,
                "goal": plan.goal,
                "step_count": len(plan.steps),
                "trace_id": self.context.trace_id,
            },
        )

        # 2. Execute in topological order
        try:
            ordered = plan.topological_order()
        except ValueError as exc:
            plan.status = PlanStatus.FAILED
            return AgentResult.failed(str(exc))

        step_outputs: dict[str, dict[str, Any]] = {}
        approvals_collected: list[dict[str, Any]] = []

        for step in ordered:
            # Budget check before each step
            try:
                self.context.check_all_budgets()
            except AgentBudgetExceededError as exc:
                plan.status = PlanStatus.FAILED
                self.context.log(
                    "orchestrator_budget_exceeded",
                    {"plan_id": plan.plan_id, "error": str(exc)},
                )
                return AgentResult.failed(f"Budget exceeded: {exc}")

            # Resolve inputs
            try:
                resolved_input = self._resolve_inputs(step, step_outputs)
            except AgentError as exc:
                plan.status = PlanStatus.FAILED
                return AgentResult.failed(f"Step '{step.step_id}': {exc}")

            # Run agent
            step_result = self._run_step(step, resolved_input)
            self._step_results[step.step_id] = step_result

            # Handle result
            if step_result.status == AgentStatus.FAILED:
                plan.status = PlanStatus.FAILED
                self.context.log(
                    "orchestrator_step_failed",
                    {"plan_id": plan.plan_id, "step_id": step.step_id},
                )
                return AgentResult.failed(
                    f"Step '{step.step_id}' failed: {step_result.error}",
                    output={"failed_step": step.step_id},
                )

            if step_result.status == AgentStatus.AWAITING_APPROVAL:
                approvals_collected.extend(step_result.approvals)

            step_outputs[step.step_id] = step_result.output

        # 3. Aggregate
        final_status = PlanStatus.AWAITING_APPROVAL if approvals_collected else PlanStatus.COMPLETED
        plan.status = final_status

        summary = f"Completed {len(ordered)} step(s) for: {plan.goal}"
        self.context.log(
            "orchestrator_plan_end",
            {
                "plan_id": plan.plan_id,
                "status": final_status.value,
                "step_count": len(ordered),
            },
        )

        return AgentResult(
            status=(
                AgentStatus.COMPLETED if not approvals_collected else AgentStatus.AWAITING_APPROVAL
            ),
            output={"plan_id": plan.plan_id, "step_outputs": step_outputs},
            summary=summary,
            approvals=approvals_collected,
            usage={
                "steps": self.context.usage.steps,
                "tool_calls": self.context.usage.tool_calls,
                "elapsed_seconds": round(self.context.usage.elapsed_seconds, 3),
            },
        )

    # ==========================================================
    # Internal helpers
    # ==========================================================

    def _run_step(self, step: PlanStep, resolved_input: dict[str, Any]) -> AgentResult:
        """Run a single step by looking up the agent and executing it."""
        try:
            agent_cls = AgentRegistry.get(step.agent_name)
        except AgentError as exc:
            return AgentResult.failed(f"Cannot find agent '{step.agent_name}': {exc}")

        agent = agent_cls(self.context)
        return agent.execute(resolved_input)

    def _resolve_inputs(
        self,
        step: PlanStep,
        step_outputs: dict[str, dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Resolve placeholders in step input.

        Placeholders look like "${step_id.field}" or "${step_id.field.subfield}".
        """
        resolved: dict[str, Any] = {}
        for key, value in step.input_data.items():
            resolved[key] = self._resolve_value(value, step_outputs)
        return resolved

    def _resolve_value(
        self,
        value: Any,
        step_outputs: dict[str, dict[str, Any]],
    ) -> Any:
        """Recursively resolve a value."""
        if isinstance(value, str):
            return self._resolve_string(value, step_outputs)
        if isinstance(value, dict):
            return {k: self._resolve_value(v, step_outputs) for k, v in value.items()}
        if isinstance(value, list):
            return [self._resolve_value(v, step_outputs) for v in value]
        return value

    def _resolve_string(
        self,
        value: str,
        step_outputs: dict[str, dict[str, Any]],
    ) -> Any:
        """Resolve a string; if it's a pure placeholder, return typed value."""
        # Full placeholder: "${step_id.field}"
        if value.startswith("${") and value.endswith("}") and value.count("${") == 1:
            path = value[2:-1]
            return self._lookup_path(path, step_outputs)

        # Inline placeholders inside a string
        import re

        def repl(match: "re.Match[str]") -> str:
            path = match.group(1)
            found = self._lookup_path(path, step_outputs)
            return str(found) if found is not None else ""

        return re.sub(r"\$\{([^}]+)\}", repl, value)

    def _lookup_path(
        self,
        path: str,
        step_outputs: dict[str, dict[str, Any]],
    ) -> Any:
        """Look up a dotted path like 'step1.field.subfield'."""
        parts = path.split(".")
        if not parts:
            return None

        step_id = parts[0]
        if step_id not in step_outputs:
            raise AgentError(f"Step '{step_id}' has no output (not yet executed or failed).")

        current: Any = step_outputs[step_id]
        for part in parts[1:]:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None

        return current

    # ==========================================================
    # Inspection
    # ==========================================================

    def get_step_result(self, step_id: str) -> AgentResult | None:
        """Return the result of a specific step, if available."""
        return self._step_results.get(step_id)

    def all_step_results(self) -> dict[str, AgentResult]:
        """Return a copy of all step results."""
        return dict(self._step_results)
